train_args:
  num_epochs: 1 
  learning_rate: 2.0e-4
  weight_decay: 0.01
  warmup_steps: 700
  cooldown_steps: null
  checkpoint: null
  wandb: true
  wandb_project_name: "text-contrastors"
  wandb_run_name: "pythia-grad-cache-160m"
  wandb_entity: "gpt4all"
  log_grads_every: 100
  log_lr_every: 10
  save_every: 2500 
  chunk_size: 2048
  output_dir: "ckpts/pythia-grad-cache-160m"
  # if using deepspeed, this will be ignored
  schedule_type: "cosine"
  max_grad_norm: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  grad_cache: true
  loss_fn: "clip"
  use_fp8: false
  clamp_logits: false
  logit_max: 100

model_args:
  logit_scale: 50
  trainable_logit_scale: false
  model_type: "encoder"
  seq_len: 128
  pooling: "last"
  encoder: false
  add_prefix: true
  tokenizer_name: "EleutherAI/pythia-160m"
  model_name: "EleutherAI/pythia-160m"
  gradient_checkpointing: false

contrastive_data_args:
  input_shards: "configs/data/contrastive_pretrain.yaml"
  workers: 0 
  batch_size: 16384
  seed: 42
  shuffle: false
  download: true
